Repository viktorfrom/d7024e-kademlia, pull requests merged in 2020-09, with the labels that each got.

#22 Docker setup with server/client example
  .github/workflows/go.yml
  Dockerfile
  README.md
  cmd/kademlia/kademlia.go
  docker-compose.yml
  go.mod
  go.yml
  internal/bucket/bucket.go
  internal/kademlia/contact.go
  internal/kademlia/kademlia.go
  internal/kademlia/kademliaid.go
  internal/network/network.go
  internal/routing/routingtable.go
  internal/routing/routingtable_test.go
  serverClient.go
  serverClient_test.go
Labels: environment

#23 Change internal structure to unbreak dependencies
  .github/workflows/go.yml
  internal/network/network.go
  internal/routing/bucket.go
  internal/routing/routingtable.go
  internal/routing/routingtable_test.go
Labels: bug

#26 Udp server
  cmd/kademlia/kademlia.go
  internal/network/network.go
  serverClient.go
  serverClient_test.go
Labels: feature

#31 Cli prototype
  .gitignore
  cmd/kademlia/cli.go
  go.mod
  go.sum
Labels: feature

#32 Init node and remade package structure
  .github/workflows/go.yml
  Dockerfile
  cmd/kademlia/cli.go
  cmd/kademlia/kademlia.go
  internal/kademlia/bucket.go
  internal/kademlia/kademlia.go
  internal/kademlia/kademliaid_test.go
  internal/kademlia/network.go
  internal/kademlia/routingtable.go
  internal/kademlia/routingtable_test.go
Labels: enhancement

#33 Rpc interface
  go.mod
  go.sum
  internal/kademlia/kademlia.go
  internal/kademlia/network.go
  internal/rpc/rpc.go
  internal/rpc/rpc_test.go
  pkg/randarr/randarr.go
  pkg/randarr/randarr_test.go
Labels: enhancement

#34 Update CLI
  cmd/kademlia/cli.go
  cmd/kademlia/commands.go
  cmd/kademlia/kademlia.go
  cmd/kademlia/prompt.txt
  go.sum
  internal/kademlia/kademlia.go
Labels: enhancement

#35 Unit Tests of given lab code
  go.sum
  internal/kademlia/bucket_test.go
  internal/kademlia/contact_test.go
  internal/kademlia/kademliaid_test.go
  internal/kademlia/routingtable_test.go
  internal/rpc/rpc.go
  internal/rpc/rpc_test.go
Labels: test

#37 Update RoutingTable when sending and reviewing ping
  cmd/kademlia/commands.go
  cmd/kademlia/kademlia.go
  internal/kademlia/bucket.go
  internal/kademlia/bucket_test.go
  internal/kademlia/kademlia.go
  internal/kademlia/network.go
  internal/kademlia/routingtable.go
  internal/kademlia/routingtable_test.go
  internal/rpc/rpc.go
  internal/rpc/rpc_test.go
Labels: enhancement

#42 Find node rpc
  go.mod
  go.sum
  internal/kademlia/bucket.go
  internal/kademlia/bucket_test.go
  internal/kademlia/contact.go
  internal/kademlia/network.go
  internal/kademlia/node.go
  internal/kademlia/nodeid.go
  internal/kademlia/rpc.go
  internal/kademlia/rpc_test.go
Labels: documentation, enhancement, feature

#44 Test coverage script
  .gitignore
  scripts/testcoverage.sh
Labels: test

#48 Join network
  cmd/kademlia/commands.go
  cmd/kademlia/kademlia.go
  internal/kademlia/network_test.go
  internal/kademlia/node.go
  internal/kademlia/node_test.go
  internal/kademlia/routingtable.go
Labels: enhancement, test

#51 Add STORE RPC primitive
  internal/kademlia/network.go
  internal/kademlia/node.go
  internal/kademlia/node_test.go
Labels: feature

#53 add custom logger for kademlia
  internal/logger/logger.go
  internal/logger/logger_test.go
Labels: enhancement

#54 Node Lookup according to Kademlia Specification
  cmd/kademlia/commands.go
  docker-compose.yml
  internal/kademlia/bucket.go
  internal/kademlia/contact.go
  internal/kademlia/network.go
  internal/kademlia/node.go
Labels: enhancement

#55 store a value on the K closest nodes to the SHA1 hash of that value
  internal/kademlia/bucket.go
  internal/kademlia/node.go
Labels: feature

#56 Find
  cmd/kademlia/commands.go
  internal/kademlia/node.go
Labels: feature

#68 Add more unit tests for cmd and network
  cmd/kademlia/cli.go
  cmd/kademlia/commands.go
  cmd/kademlia/commands_test.go
  cmd/kademlia/kademlia.go
  cmd/kademlia/prompt.txt
  internal/kademlia/network.go
  internal/kademlia/network_test.go
  internal/kademlia/routingtable_test.go
Labels: test

#70 Update Kademlia to use TargetID in RPC calls
  internal/kademlia/network.go
  internal/kademlia/network_test.go
  internal/kademlia/node.go
  internal/kademlia/rpc.go
  internal/kademlia/rpc_test.go
Labels: bug, test

#71 Workflows check test coverage
  .github/workflows/go.yml
  scripts/get-total-coverage.sh
Labels: enhancement
